/**
 * Input field configurations for all transaction models
 *
 * Defines the inputs needed for each model in a data-driven way,
 * enabling dynamic form generation.
 */

export interface InputFieldConfig {
  id: string;
  label: string;
  type: 'text' | 'number' | 'select';
  options?: Array<{ value: string; label: string }>;
  min?: number;
  max?: number;
  step?: number;
  hint?: string;
  category?: 'basic' | 'cost' | 'revenue' | 'tax' | 'timing';
  /** Industry standard benchmark label (e.g., "Industry: 5-15%") */
  benchmark?: string;
  /** Whether this is an essential input shown by default (vs advanced) */
  essential?: boolean;
}

// Common fields used across multiple models
const commonFields: Record<string, InputFieldConfig> = {
  projectName: {
    id: 'projectName',
    label: 'Project Name',
    type: 'text',
    category: 'basic',
    essential: true,
  },
  developmentCost: {
    id: 'developmentCost',
    label: 'Development Cost (R)',
    type: 'number',
    min: 0,
    step: 10000,
    category: 'cost',
    essential: true,
  },
  researchPhaseCost: {
    id: 'researchPhaseCost',
    label: 'Research Phase Cost (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Expensed under IAS 38',
    category: 'cost',
    essential: false,
  },
  developmentPhaseCost: {
    id: 'developmentPhaseCost',
    label: 'Development Phase Cost (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Capitalised under IAS 38',
    category: 'cost',
    essential: false,
  },
  usefulLife: {
    id: 'usefulLife',
    label: 'Useful Life (Years)',
    type: 'number',
    min: 1,
    max: 20,
    step: 1,
    category: 'timing',
    benchmark: 'Typical: 3-10 years',
    essential: false,
  },
  section11eType: {
    id: 'section11eType',
    label: 'Tax Write-Off Period',
    type: 'select',
    options: [
      { value: 'pc-2yr', label: 'Standard Software (2-year)' },
      { value: 'mainframe-5yr', label: 'Complex Systems (5-year)' },
    ],
    category: 'tax',
    essential: false,
  },
  corporateTaxRate: {
    id: 'corporateTaxRate',
    label: 'Corporate Tax Rate (%)',
    type: 'number',
    min: 0,
    max: 50,
    step: 1,
    category: 'tax',
    benchmark: 'SA: 27%',
    essential: false,
  },
};

// Model 1: Cost-Plus input fields
const model1Fields: InputFieldConfig[] = [
  commonFields.projectName,
  commonFields.developmentCost,
  commonFields.researchPhaseCost,
  commonFields.developmentPhaseCost,
  {
    id: 'markupPercentage',
    label: 'Markup Percentage (%)',
    type: 'number',
    min: 0,
    max: 50,
    step: 1,
    hint: "Arm's length range: 5-15%",
    category: 'revenue',
    benchmark: 'Industry: 5-15%',
    essential: true,
  },
  commonFields.usefulLife,
  commonFields.section11eType,
  commonFields.corporateTaxRate,
];

// Model 2: Licence input fields
const model2Fields: InputFieldConfig[] = [
  commonFields.projectName,
  commonFields.developmentCost,
  commonFields.researchPhaseCost,
  commonFields.developmentPhaseCost,
  {
    id: 'developerUsefulLife',
    label: 'Developer Useful Life (Years)',
    type: 'number',
    min: 1,
    max: 20,
    step: 1,
    hint: 'How long developer will amortise the IP',
    category: 'timing',
    essential: false,
  },
  {
    id: 'upfrontLicenceFee',
    label: 'Upfront Licence Fee (R)',
    type: 'number',
    min: 0,
    step: 10000,
    category: 'revenue',
    benchmark: 'Varies by scope',
    essential: true,
  },
  {
    id: 'licenceType',
    label: 'Licence Type',
    type: 'select',
    options: [
      { value: 'perpetual', label: 'Perpetual' },
      { value: 'term', label: 'Term-based' },
    ],
    category: 'basic',
    essential: true,
  },
  {
    id: 'licenceTerm',
    label: 'Licence Term (Years)',
    type: 'number',
    min: 1,
    max: 20,
    step: 1,
    hint: 'For term-based licences',
    category: 'timing',
  },
  {
    id: 'exclusivity',
    label: 'Exclusivity',
    type: 'select',
    options: [
      { value: 'exclusive', label: 'Exclusive' },
      { value: 'non-exclusive', label: 'Non-Exclusive' },
    ],
    category: 'basic',
  },
  {
    id: 'territory',
    label: 'Territory',
    type: 'select',
    options: [
      { value: 'south-africa', label: 'South Africa' },
      { value: 'africa', label: 'Africa' },
      { value: 'global', label: 'Global' },
    ],
    category: 'basic',
  },
  {
    id: 'sourceCodeAccess',
    label: 'Source Code Access',
    type: 'select',
    options: [
      { value: 'none', label: 'None' },
      { value: 'escrow', label: 'Escrow' },
      { value: 'full', label: 'Full Access' },
    ],
    hint: 'Whether buyer has access to source code',
    category: 'basic',
  },
  {
    id: 'buyerUsefulLife',
    label: 'Buyer Useful Life (Years)',
    type: 'number',
    min: 1,
    max: 20,
    step: 1,
    hint: 'How long buyer will amortise the licence',
    category: 'timing',
  },
  {
    id: 'implementationCosts',
    label: 'Implementation Costs (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Costs incurred by buyer to implement',
    category: 'cost',
  },
  commonFields.section11eType,
  commonFields.corporateTaxRate,
];

// Model 3: Joint Development input fields
const model3Fields: InputFieldConfig[] = [
  commonFields.projectName,
  {
    id: 'totalProjectCost',
    label: 'Total Project Cost (R)',
    type: 'number',
    min: 0,
    step: 10000,
    category: 'cost',
  },
  commonFields.researchPhaseCost,
  commonFields.developmentPhaseCost,
  {
    id: 'projectDurationMonths',
    label: 'Project Duration (Months)',
    type: 'number',
    min: 1,
    max: 60,
    step: 1,
    category: 'timing',
  },
  {
    id: 'developerCashContribution',
    label: 'Developer Cash Contribution (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Your cash investment',
    category: 'cost',
  },
  {
    id: 'developerPersonnelFTEs',
    label: 'Developer Personnel (FTEs)',
    type: 'number',
    min: 0,
    max: 50,
    step: 0.5,
    hint: 'Full-time equivalents from your team',
    category: 'cost',
  },
  {
    id: 'developerPersonnelCostPerMonth',
    label: 'Developer Personnel Cost/Month (R)',
    type: 'number',
    min: 0,
    step: 5000,
    hint: 'Average monthly cost per FTE',
    category: 'cost',
  },
  {
    id: 'developerIPContribution',
    label: 'Developer IP Contribution (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Value of existing IP contributed',
    category: 'cost',
  },
  {
    id: 'developerFacilitiesContribution',
    label: 'Developer Facilities Contribution (R)',
    type: 'number',
    min: 0,
    step: 5000,
    hint: 'Value of facilities/equipment contributed',
    category: 'cost',
  },
  {
    id: 'buyerCashContribution',
    label: 'Client Cash Contribution (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Client cash investment',
    category: 'cost',
  },
  {
    id: 'buyerPersonnelFTEs',
    label: 'Client Personnel (FTEs)',
    type: 'number',
    min: 0,
    max: 50,
    step: 0.5,
    hint: 'Full-time equivalents from client',
    category: 'cost',
  },
  {
    id: 'buyerPersonnelCostPerMonth',
    label: 'Client Personnel Cost/Month (R)',
    type: 'number',
    min: 0,
    step: 5000,
    hint: 'Average monthly cost per FTE',
    category: 'cost',
  },
  {
    id: 'buyerIPContribution',
    label: 'Client IP Contribution (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Value of client IP contributed',
    category: 'cost',
  },
  {
    id: 'buyerDomainExpertiseValue',
    label: 'Client Domain Expertise Value (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Value of domain knowledge contributed',
    category: 'cost',
  },
  {
    id: 'valuationMethod',
    label: 'Valuation Method',
    type: 'select',
    options: [
      { value: 'cost-basis', label: 'Cost Basis' },
      { value: 'fair-value', label: 'Fair Value' },
    ],
    category: 'basic',
  },
  commonFields.usefulLife,
  commonFields.section11eType,
  commonFields.corporateTaxRate,
];

// Model 4: BOT input fields
const model4Fields: InputFieldConfig[] = [
  commonFields.projectName,
  commonFields.developmentCost,
  commonFields.researchPhaseCost,
  commonFields.developmentPhaseCost,
  {
    id: 'operationPeriodYears',
    label: 'Operation Period (Years)',
    type: 'number',
    min: 1,
    max: 10,
    step: 1,
    hint: 'How long developer operates before transfer',
    category: 'timing',
  },
  {
    id: 'annualOperatingFee',
    label: 'Annual Operating Fee (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Fee charged to client during operation',
    category: 'revenue',
  },
  {
    id: 'annualOperatingCost',
    label: 'Annual Operating Cost (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Your cost to operate the system',
    category: 'cost',
  },
  {
    id: 'estimatedAnnualRevenue',
    label: 'Estimated Annual Revenue (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Expected revenue generated by system',
    category: 'revenue',
  },
  {
    id: 'transferYear',
    label: 'Transfer Year',
    type: 'number',
    min: 1,
    max: 10,
    step: 1,
    hint: 'When ownership transfers to client',
    category: 'timing',
  },
  {
    id: 'fixedTransferPrice',
    label: 'Transfer Price (R)',
    type: 'number',
    min: 0,
    step: 10000,
    hint: 'Price at which ownership transfers',
    category: 'revenue',
  },
  {
    id: 'inflationAdjustment',
    label: 'Inflation Adjustment (%)',
    type: 'number',
    min: 0,
    max: 20,
    step: 0.5,
    hint: 'Annual price escalation',
    category: 'revenue',
  },
  commonFields.usefulLife,
  commonFields.section11eType,
  commonFields.corporateTaxRate,
];

// Model 5: Software Sale input fields
const model5Fields: InputFieldConfig[] = [
  commonFields.projectName,
  commonFields.developmentCost,
  commonFields.researchPhaseCost,
  commonFields.developmentPhaseCost,
  {
    id: 'salePrice',
    label: 'Sale Price (R)',
    type: 'number',
    min: 0,
    step: 10000,
    category: 'revenue',
    benchmark: 'Typically 1.5-3x dev cost',
    essential: true,
  },
  {
    id: 'paymentTerms',
    label: 'Payment Terms',
    type: 'select',
    options: [
      { value: 'upfront', label: 'Upfront' },
      { value: 'milestone', label: 'Milestone-based' },
      { value: 'deferred', label: 'Deferred' },
      { value: 'earnout', label: 'Earnout' },
    ],
    category: 'revenue',
    essential: true,
  },
  {
    id: 'annualMaintenanceFee',
    label: 'Annual Maintenance Fee (R)',
    type: 'number',
    min: 0,
    step: 1000,
    hint: 'Fee charged for ongoing maintenance',
    category: 'revenue',
  },
  {
    id: 'annualMaintenanceCost',
    label: 'Annual Maintenance Cost (R)',
    type: 'number',
    min: 0,
    step: 1000,
    hint: 'Your cost to provide maintenance',
    category: 'cost',
  },
  {
    id: 'maintenanceTerm',
    label: 'Maintenance Term (Years)',
    type: 'number',
    min: 1,
    max: 10,
    step: 1,
    hint: 'Duration of maintenance agreement',
    category: 'timing',
  },
  commonFields.usefulLife,
  commonFields.section11eType,
  commonFields.corporateTaxRate,
];

// Model 6: SaaS input fields
const model6Fields: InputFieldConfig[] = [
  commonFields.projectName,
  commonFields.developmentCost,
  commonFields.researchPhaseCost,
  commonFields.developmentPhaseCost,
  {
    id: 'monthlySubscriptionFee',
    label: 'Monthly Subscription Fee (R)',
    type: 'number',
    min: 0,
    step: 1000,
    category: 'revenue',
    essential: true,
  },
  {
    id: 'contractLengthMonths',
    label: 'Contract Length (Months)',
    type: 'number',
    min: 1,
    max: 60,
    step: 1,
    category: 'timing',
    benchmark: 'Typical: 12-36 months',
    essential: true,
  },
  {
    id: 'pricingModel',
    label: 'Pricing Model',
    type: 'select',
    options: [
      { value: 'flat-rate', label: 'Flat Rate' },
      { value: 'per-user', label: 'Per User' },
      { value: 'usage-based', label: 'Usage Based' },
    ],
    category: 'basic',
    essential: true,
  },
  {
    id: 'annualHostingCost',
    label: 'Annual Hosting Cost (R)',
    type: 'number',
    min: 0,
    step: 1000,
    hint: 'Infrastructure and hosting expenses',
    category: 'cost',
  },
  {
    id: 'annualSupportCost',
    label: 'Annual Support Cost (R)',
    type: 'number',
    min: 0,
    step: 1000,
    hint: 'Customer support and maintenance costs',
    category: 'cost',
  },
  commonFields.usefulLife,
  commonFields.section11eType,
  commonFields.corporateTaxRate,
];

// Export all field configurations by model ID
export const modelFieldConfigs: Record<string, InputFieldConfig[]> = {
  'model-1': model1Fields,
  'model-2': model2Fields,
  'model-3': model3Fields,
  'model-4': model4Fields,
  'model-5': model5Fields,
  'model-6': model6Fields,
};
